export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const DECREASE = "DECREASE";
export const INCREASE = "INCREASE";
export const DELETE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP = "USER_SIGNUP";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
